version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: tahoo-mysql
    volumes:
      - "./tahoo-mysql:/var/lib/mysql"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: tahoo_db
      MYSQL_USER: tahoo-root
      MYSQL_PASSWORD: 123456

#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    container_name: onehs-zookeeper
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#      - 22181:2181
#
#  kafka:
#    image: confluentinc/cp-kafka:latest
#    container_name: onehs-kafka
#    depends_on:
#       - zookeeper
#    ports:
#      - 29092:29092
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
#    container_name: onehs-eslasticsearch
#    environment:
#      - discovery.type=single-node
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ports:
#      - 9200:9200
#    volumes:
#      - "./onees:/usr/share/elasticsearch/data"