version: '3'

services:
  cabin_db:
    image: mysql:latest
    container_name: onehs-mysql-container
    volumes:
#      - "C:/onedb:/var/lib/mysql"
      - "/home/user/desktop/onedb:/var/lib/mysql"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: onehs_db
      MYSQL_USER: onehs-root
      MYSQL_PASSWORD: 123456