
 spring.datasource:
    url: jdbc:mysql://localhost:3306/onehs_db
    username: onehs-root
    password: 123456
 spring:
    jpa:
      database-platform: org.hibernate.dialect.MySQL5Dialect
      open-in-view: false
      hibernate:
        ddl-auto: update
        use-new-id-generator-mappings: false
        naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties.hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      properties:
        hibernate:
          globally_quoted_identifiers: true
    kafka:
      consumer:
        bootstrap-servers: localhost:9092
        group-id: topics-cusumer
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      producer:
        bootstrap-servers: localhost:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer


